### ISSUE TITLE
How to Run, Test or Deploy

### ISSUE THREAD

**Issue by dancesWithCycles** [entur/mobility-map-demo#48]
Hi folks,
Thank you so much for providing this repository. It looks promising. Do you mind providing me with an idea on how to run, test or deploy this repository?

Calling ```npm install``` in the root directory with Node.js version ```v17.7.1``` failed. Is there a recommended Node.js version?

Cheers!

**Comment by testower** [comment]
Same as https://github.com/entur/vehicle-map-demo/issues/45
